### PR TITLE
Change to GitHub + Updated to v2.5.0

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Needed for https://github.com/conda-forge/libignition-fuel-tools-feedstock/pull/8

**Comment by Tobias-Fischer** [comment]
This is ready to be merged @conda-forge/libignition-cmake0

**Review by traversaro — APPROVED** [review]
Thanks @Tobias-Fischer , the change seems ok for me. However, I still do not have a lot of experience with conda-forge, so it may be better to have another review before merging.

**Comment by seanyen** [comment]
LGTM. Thanks for the contribution!

**Pull request merged**
